import { StyleSheet } from "react-native";
import { colors } from "../Config/colorpallete";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
    paddingHorizontal: 16,
    paddingTop: 40,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  menuButton: {
    backgroundColor: colors.whiteSmoke,
    padding: 8,
    borderRadius: 999,
  },
  delivery: {
    marginLeft: 8,
  },
  deliverTo: {
    fontSize: 10,
    color: colors.brand,
    fontWeight: "600",
  },
  locationRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  locationText: {
    fontWeight: "600",
    color: colors.textSecondary,
  },
  cartButton: {
    position: "relative",
    backgroundColor: colors.black,
    padding: 8,
    borderRadius: 999,
  },
  cartBadge: {
    position: "absolute",
    top: -4,
    right: -4,
    backgroundColor: colors.brand,
    width: 16,
    height: 16,
    borderRadius: 999,
    justifyContent: "center",
    alignItems: "center",
  },
  cartBadgeText: {
    color: colors.white,
    fontSize: 9,
    fontWeight: "700",
  },
  greeting: {
    marginTop: 24,
    fontSize: 16,
    color: colors.black,
  },
  greetingBold: {
    fontWeight: "700",
  },
  searchBar: {
    marginTop: 16,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.whiteSmoke,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  searchInput: {
    marginLeft: 8,
    flex: 1,
    fontSize: 14,
    color: colors.textSecondary,
  },
  sectionHeader: {
    marginTop: 24,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.black,
  },
  seeAll: {
    fontSize: 14,
    fontWeight: "500",
    color: colors.brand,
  },
  categoriesScroll: {
    marginTop: 12,
  },
  categoryCard: {
    marginRight: 16,
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 8,
    alignItems: "center",
    width: 80,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 2,
  },
  categoryImage: {
    width: 56,
    height: 56,
    borderRadius: 12,
    backgroundColor: colors.lightGray,
  },
  categoryName: {
    marginTop: 8,
    fontSize: 12,
    fontWeight: "600",
    color: colors.textSecondary,
  },
  restaurantCard: {
    marginTop: 16,
    backgroundColor: colors.white,
    borderRadius: 16,
    paddingBottom: 12,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 2,
  },
  restaurantImage: {
    width: "100%",
    height: 160,
    borderRadius: 16,
    backgroundColor: colors.lightGray,
  },
  restaurantInfo: {
    marginTop: 8,
    paddingHorizontal: 8,
  },
  restaurantName: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.textPrimary,
  },
  restaurantDesc: {
    fontSize: 12,
    color: colors.midGray,
    marginTop: 4,
  },
  restaurantMeta: {
    flexDirection: "row",
    marginTop: 8,
    alignItems: "center",
  },
  metaItem: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 12,
  },
  metaText: {
    fontSize: 12,
    marginLeft: 4,
    color: colors.textSecondary,
  },
  bannerScroll: {
    marginTop: 20,
  },
  bannerImage: {
    width: 300,
    height: 120,
    borderRadius: 16,
    marginRight: 12,
  },
  foodCard: {
    width: 120,
    backgroundColor: colors.white,
  borderRadius: 16,
  padding: 8,
  marginRight: 12,
  shadowColor: "#000",
  shadowOpacity: 0.05,
  shadowOffset: { width: 0, height: 2 },
  shadowRadius: 4,
  elevation: 2,
  alignItems: "center",
},
foodImage: {
  width: 100,
  height: 100,
  borderRadius: 16,
  backgroundColor: colors.lightGray,
},
foodName: {
  marginTop: 8,
  fontSize: 14,
  fontWeight: "600",
  color: colors.textPrimary,
  textAlign: "center",
},
foodPrice: {
  fontSize: 12,
  color: colors.brand,
  marginTop: 4,
},
interactiveSection: {
  marginTop: 24,
  paddingHorizontal: 0,
},
quickLinkCard: {
  width: 100,
  height: 100,
  borderRadius: 16,
  backgroundColor: colors.info,
  marginRight: 12,
  justifyContent: "center",
  alignItems: "center",
},
quickLinkText: {
  color: colors.white,
  fontWeight: "600",
  marginTop: 8,
  textAlign: "center",
},
mustTryCard: {
  width: 140,
  borderRadius: 16,
  padding: 8,
  marginRight: 12,
  shadowColor: colors.black,
  shadowOpacity: 0.05,
  shadowOffset: { width: 0, height: 2 },
  shadowRadius: 4,
  elevation: 2,
  alignItems: "center",
  position: "relative",
},
  badge: {
  position: "absolute",
  top: 8,
  left: 8,
  backgroundColor: colors.brand,
  paddingHorizontal: 6,
  paddingVertical: 2,
  borderRadius: 8,
  zIndex: 10,
},
badgeText: {
  color: colors.white,
  fontSize: 10,
  fontWeight: "700",
},
});
